### ISSUE TITLE
no longer works under ubuntu 16.4

### ISSUE THREAD

**Issue by NikosEfthias** [robertohuertasm/vscode-icons#113]
today when i open noticed that icons are not working anymore the `/usr/share/code` forlder is owned by me and the exnsion is enabled but its no working

**Comment by robertohuertasm** [comment]
Can anyone confirm this? I'm on holidays and have limited access to the internet and linux vms 😞

**Comment by ekmlarbi** [comment]
Yes its just as @NikosEfthias said. In my case I had it running in vscode 1.0.0 on 16.04. After upgrading to vscode 1.3.1 today it stopped working. My ownership of the folder `/usr/share/code` is intact and I have enabled the extension.

**Comment by robertohuertasm** [comment]
Which version of the extension are you running?

**Comment by robertohuertasm** [comment]
@NikosEfthias can you tell me if it stopped working with the latest version of the extension?  Can you both open the dev tools in your vscode and let me know what you see in there?

**Comment by ekmlarbi** [comment]
@robertohuertasm, Here is what I am using:
vscode-icons [1.5.2],
vscode [1.3.1]
Let me know what i should be looking for in vscode devtool.

**Comment by robertohuertasm** [comment]
I've tested it with Ubuntu 15.04 and it's working perfectly. Unfortunately, I have no full internet access and can't access to 16.04. @ekmlarbi, take a look into the console and look for error messages.

**Comment by robertohuertasm** [comment]
Have you tried reinstalling VS Code?

**Comment by birz4man** [comment]
Same here :(  i am using ubuntu 16.04

**Comment by robertohuertasm** [comment]
@birz4man can you look into the dev tools and look for some error messages?

**Comment by NikosEfthias** [comment]
there is no error on the developer tools 
![](http://i.imgur.com/be4PUR5.png)

**Comment by NikosEfthias** [comment]
1.5.2 btw my vscode-icons version is and 1.3.1 vscode version

**Comment by robertohuertasm** [comment]
Any of you have tried reinstalling vscode?

**Comment by NikosEfthias** [comment]
now trying give me a sec :)

**Comment by birz4man** [comment]
OK :) nikos help me now. Thx nikos i fixed :)

**Comment by robertohuertasm** [comment]
@birz4man what did you do?

**Comment by NikosEfthias** [comment]
he just didnt own the /usr/share/code folder @robertohuertasm

**Comment by robertohuertasm** [comment]
ok, but I guess you're still having the issue, aren't you? Or did reinstalling do the trick?

**Comment by NikosEfthias** [comment]
i just reinstalled and still not working this happened after the latest update only before it was working @robertohuertasm

**Comment by robertohuertasm** [comment]
For what we know @birz4man has your same settings. @birz4man can you confirm this?

**Comment by birz4man** [comment]
yes @robertohuertasm

**Comment by robertohuertasm** [comment]
@NikosEfthias The most strange thing is you not seeing some errors in the console. A lack of permissions will trigger a vscode warning and any other thing will raise an error... or it should have to raise an error... clearly there's something that we're missing. Reinstalling should leave your original files cleaned... have you tried with "icons update" command? 
Btw, thanks @birz4man for confirming this.

**Comment by NikosEfthias** [comment]
just issued that command and it broke vscode entirely vscode wont start

**Comment by NikosEfthias** [comment]
![](http://i.imgur.com/u1wyTf8.png)

**Comment by NikosEfthias** [comment]
even after i uninstall extension from command line vscode is not working now

**Comment by robertohuertasm** [comment]
Reinstall vscode and all should be working again. Are you using Insiders version? Breaking when updating means something failed while restoring the backup. This command disables and enables again the extension by setting vscode to its original state and then applying again the extension patches.

**Comment by NikosEfthias** [comment]
I have both insider and normal but the extension is installed on normal
version

**Comment by NikosEfthias** [comment]
i reinstalled it is fine now and i am using both insider and normal and extension is installed under normal one not insider

**Comment by robertohuertasm** [comment]
If you feel like it download the project and debug it in your vscode. I cannot reproduce it on my 15.04 and won't have access to 16.04 until next Monday. This is the way to go to know what's really happening.

**Comment by robertohuertasm** [comment]
When you say it's fine are you referring to your vscode or to the extension?

**Comment by NikosEfthias** [comment]
vscode is fine extension is still not working after reinstalling both vscode and extension but the update command just breaks everything

**Comment by robertohuertasm** [comment]
Just to be sure. You install the extension and restart vscode. Then run "icons enable" command,  restart again and no errors in your console. If that's the case, debugging the extension is the way to go. I'll do it myself on Monday if you can wait and can reproduce it. The strangest thing is that @birz4man seems to have the same settings and it's working for him...

**Comment by ScenK** [comment]
Same issue on Mac. Re-install the extension could work.

**Comment by robertohuertasm** [comment]
@ScenK I have a Mac and it's working (normal and insiders). Could you let me know what you see in the dev tools console? Did it work when you reinstalled it?

**Comment by ScenK** [comment]
@robertohuertasm Yes, it works after i reinstalled.

**Comment by jeffstahlin** [comment]
I just had the same issue on Ubuntu 16.10. My folder permissions for the /user/share/code were username:root which seemed to be fine until the latest update of vscode-icons, 1.5.5. I tried updating the icons, enabling them etc. but nothing worked. What fixed it for me was to change ownership of the /usr/share/code folder to username:username and then opening VS Code and enabling/updating icons (I did both).

**Comment by jens1o** [comment]
@jeffstahlin Could you provide the command you used? I'll add them into the readme.

**Comment by NikosEfthias** [comment]
updating icont broke my vscode entirely last time now let me try the group ownership hopefully its gonna work :)

**Comment by NikosEfthias** [comment]
nope it makes no difference @jeffstahlin

**Comment by jens1o** [comment]
Please give us the error code.

**Comment by NikosEfthias** [comment]
as i shared the ss before theres no error thrown 
@jens1o

**Comment by robertohuertasm** [comment]
@NikosEfthias did you tried a clean install and then giving group ownership?

**Comment by NikosEfthias** [comment]
yes i even installed vscode from scratch

**Comment by robertohuertasm** [comment]
I've just tested it in Ubuntu 16.04, clean install and all seems to be working. Just to be clear, you say you reinstall the app, then do "icons enable", restart, and nothing happens, is that right? Can you send us a screenshot of your explorer tree?

**Comment by robertohuertasm** [comment]
Go to:
```sh
cd /usr/share/code/resources/app/out/vs/workbench
```
and look for workbench.main.css.bak and workbench.main.js.bak? Can you find those files?

**Comment by robertohuertasm** [comment]
> just issued that command and it broke vscode entirely vscode wont start
If that's so this means somehow your bak files have not been restored properly. Delete VsCode folder and reinstall again.

**Comment by NikosEfthias** [comment]
![](http://i.imgur.com/uRPOQiV.png) here is the tree
![](http://i.imgur.com/XSN6d5r.png) update command
![](http://i.imgur.com/S0WXxPh.png) after restart
![](http://i.imgur.com/nk0KqUA.png) ownership of the folder
![](http://i.imgur.com/WwsszRU.png) contents of the folder you asked @robertohuertasm

**Comment by jens1o** [comment]
Are they any errors in the dev console?

**Comment by robertohuertasm** [comment]
Can you send me your workbench.main.js and the bad file by email? roberto.huertas[at]outlook.com

**Comment by NikosEfthias** [comment]
what do you mean the bad file ? @robertohuertasm 
and no there are no errors @jens1o

**Comment by NikosEfthias** [comment]
[here](https://gist.github.com/1893ae571f095c87d54c9dfd455e1a75) you can see the file

**Comment by robertohuertasm** [comment]
It was .bak file... I was typing from a mobile phone....

**Comment by robertohuertasm** [comment]
@NikosEfthias it's strange. Your workbench.main.js is not modified at all... could you follow this steps and show me this file again after following them?
- Execute "Icons Disable" and make sure the .bak files are gone from the folder.
- Restart and execute "Icons Enable".
- Restart again.
- Send me workbench.main.js and workbench.main.js.bak please.

**Comment by jens1o** [comment]
@robertohuertasm Are you fully sure that you can catch up any permission denied error with the pattern in the main file? I think there could be some errorcode thrown that's actually not in the code.

**Comment by NikosEfthias** [comment]
now i am doing the instructions @robertohuertasm  wrote above i will inform you shortly

**Comment by NikosEfthias** [comment]
here we go when i say icons disable vscode entirely wont open 
this is how it looks ![](http://i.imgur.com/9laaxFl.png)

and the contents of the folder is here `bak`s are gone

![](http://i.imgur.com/yXCczQa.png)

and the content of the main file is [here](https://gist.github.com/a6264b3d25dd217344ec8491eb4b2a14)

**Comment by NikosEfthias** [comment]
couple of errors ![](http://i.imgur.com/Eyd1fWh.png)

**Comment by jens1o** [comment]
Could you please uninstall any other extension via cli?

**Comment by NikosEfthias** [comment]
@jens1o what do you mean any other extension ?

**Comment by jens1o** [comment]
Do you have other extensions installed? @NikosEfthias

**Comment by NikosEfthias** [comment]
a couple that i use

**Comment by NikosEfthias** [comment]
i can try using insiders instead of deleting all other extensions

**Comment by jens1o** [comment]
Could you disable them, so we can be sure it is vscode that causes all theses errors?

**Comment by NikosEfthias** [comment]
is it possible to disable extensions without deleting on vscode ?

**Comment by robertohuertasm** [comment]
I don't think you have todisable anything. Let me see your files.  The only extension modifying files is this one.

**Comment by jens1o** [comment]
Yes, it is possible.

Should I let you know how to disable them.

// Okey, roberto has the word.

**Comment by NikosEfthias** [comment]
@jens1o yes please let me know :) 
@robertohuertasm  what do you think the issue is ? i now downloaded insiders to try there

**Comment by jens1o** [comment]
Noo. Let's do what roberto says, he's the owner.

**Comment by NikosEfthias** [comment]
@jens1o i just wanna know how do i disable something its not about the icons :) some very useful extension becomes painful in big project folders so i can temporarily disable them

**Comment by jens1o** [comment]
Oh, I have to changed my output. It is not possible. I thought because you need to enable then once you've installed it, it is available. But it isn't....

**Comment by robertohuertasm** [comment]
I'm not really sure at the moment. What i can see is that the workbench.main.js file is not being modified, which would indicate some lack of permissions but you're not receiving any warning and the replace function doesn't write into your console, which is weird because if the modification would fail you should have a message there... so let's do something:

- Reinstall your vscode
- Be sure that you don't have any .bak file in the folder
- Uninstall the extension (restart and all the stuff).
- Check out again the folder: no .bak files should be there.
- Install the extension (restart, blah, blah)
- Execute *icons enable* but before restarting check the console for errors.
- Share with us the errors (if any) you have found and these files: workbench.main.js, workbench.main.css, workbench.main.js.bak and workbench.main.css.bak

Then, provided that you still have some errors, we'll analyse those files to find out what's happening.

**Comment by jens1o** [comment]
> @robertohuertasm Are you fully sure that you can catch up any permission denied error with the pattern in the main file? I think there could be some errorcode thrown that's actually not in the code.

**Comment by robertohuertasm** [comment]
Any non controlled error regarding permissions should be logged into the console.

**Comment by NikosEfthias** [comment]
i just now installed insiders and installed the extension seems working for insiders  let me try all you wrote above @robertohuertasm

**Comment by NikosEfthias** [comment]
![](http://i.imgur.com/3Yzw2dd.png)

from insiders

**Comment by jens1o** [comment]
Great!

**Comment by robertohuertasm** [comment]
Cool, I already tested it yesterday in Ubuntu 16.04 and for me was working in both versions.

**Comment by jens1o** [comment]
Looks not like that's a bug. Looks like there are problems with users.(No, I'm not inpolite to anyone.)

//vote4close

**Comment by NikosEfthias** [comment]
after i purge `apt-get purge` noticed that the `resources` folder was not deleted by apt hopefully deleting it and fresh install will fix the issue

**Comment by robertohuertasm** [comment]
Stable version is not really different from insiders in terms of what we currently do to make the extension work so a clean install should be working.

**Comment by robertohuertasm** [comment]
@jens1o We should know what's happening to @NikosEfthias so we can help some other people who may find the same issue. Even more, we maybe can prevent it if we knew how they make it to crash the extension in the first place. So I vote to keep it open until @NikosEfthias checks out whether the clean install works or not for him (hopefully yes) :wink:

**Comment by NikosEfthias** [comment]
here we go :+1:  it works after deleting the resources entirely the problem was i think resources were never updated and still its weird that extension didn't update the file though its owned by me whos the same user running the vscode

**Comment by NikosEfthias** [comment]
so i guess the issue can be  closed  :smile:

**Comment by NikosEfthias** [comment]
thank you so much for help finally got the icons back :)

**Comment by robertohuertasm** [comment]
Ok! So we've learnt that in case that a clean install does not work we have to manually delete the resources folder to start afresh.

**Comment by NikosEfthias** [comment]
exactly

**Comment by robertohuertasm** [comment]
@jorawarsingh can you check your dev console for messages? Can you attach a screenshot of your tree view? Have you checked that you're not behind a proxy?

**Comment by jorawarsingh** [comment]
Here i the screen shot.
![vscode-dev](https://cloud.githubusercontent.com/assets/7203792/17645496/2d9ec2f2-61a8-11e6-897e-31d28689b51e.png)
No i'm not behind proxy.

**Comment by robertohuertasm** [comment]
@jorawarsingh have you executed the "icons update" command? => F1 > Icons Update

**Comment by jorawarsingh** [comment]
now that's was tricky i got updates in the extension panel and updated from there may be three times and never worked what's the different? I have icons now +1:

**Comment by robertohuertasm** [comment]
I'm glad it's working for you know. The latest update supported auto "Icons Update" command execution but somehow yours wasn't working. You always must run this command whenever it's a new installation or update of the extension or vscode.
