### ISSUE TITLE
Icons does not show up after July 2016 vscode update

### ISSUE THREAD

**Issue by nimamarashi** [robertohuertasm/vscode-icons#140]
I did the July update for vscode and extension does not work anymore.

**Comment by robertohuertasm** [comment]
Do you mean 1.4.0? Which platform are you using? Have you follow the FAQs section in the Reame? Have you executed the Icons Update command?

**Comment by jens1o** [comment]
I can reproduce that, but with another extension.(an else statement i

I'm running on Windows 10 64 Bit, 1.4.0 Stable.

It completly crashed visual studio code in startup. The error log in the dev console says, that it couldn't parse an "else".

After installing it completly fresh, it starts working again. Something is wrong with vscode, the extension looks good.

**Comment by nimamarashi** [comment]
I'm running on Windows 10 64 Bit, version 1.5.5

I did restart the vscode after update and all icons are gone. reinstalled and enabled the extension, still same.

**Comment by rgamba** [comment]
same thing happened to me, for some reason it just stopped working after the 1.4 update

**Comment by jens1o** [comment]
Please... System Infos and Error logs from the console.

Don't matters if the window refuses to load, you always can take a log into the developer console.

**Comment by rgamba** [comment]
ok just `> Icons Update` did the trick. Working now

**Comment by jens1o** [comment]
Strange, it completly freezes and refused to load on my system... Really Strange.

**Comment by nimamarashi** [comment]
The only log on console: "vscode-icons is active!", no error.

**Comment by jens1o** [comment]
Try reinstalling vscode. @nimamarashi

**Comment by liuchenx** [comment]
os x 10.11   vscode 1.4.0 not work

**Comment by nimamarashi** [comment]
Tried "Icons Update" command and it fixed. Thank you.

**Comment by ajsb85** [comment]
Does not work for v1.4.0 and no error in the Console.

**Comment by robertohuertasm** [comment]
Please, gentlemen, a little bit more details will be really appreciated: Platform, vscode version, extension version, steps you've tried to fixed after reading the readme FAQs section. This would help in order to not repeat ourselves ad infinitum with noisy comments. :D

**Comment by ajsb85** [comment]
Extension v1.5.5
VS Code v1.4.0

Does not work after upgrade the VS Code.

**Comment by robertohuertasm** [comment]
@ajsb85 Have you tried "Icons Update"? If this wouldn't work then reinstall VSCode and try Icons Enable.

**Comment by robertohuertasm** [comment]
@ajsb85 Which platform are you using? OSX, Windows, Linux (flavour)...

**Comment by ajsb85** [comment]
@robertohuertasm Yes, I was uninstall and Install under admin environment and still hidden the icons.

**Comment by robertohuertasm** [comment]
But have you then executed the Icons Enabled command?

**Comment by ajsb85** [comment]
`Ctrl+Shift+P >Icons Enable` and after reload It's works. Thanks

**Comment by robertohuertasm** [comment]
I'm glad it worked but this is an example of something that should have been solved by reading the FAQs section of the Readme. Hopefully, @jens1o has prepared some templates for raising issues and pull requests that will be soon implemented and will eventually reduce this kind of issues. Anyway, we're here to offer support for our users so no offense, please :wink:

**Comment by robertohuertasm** [comment]
@liuchenx have you solved your problem or are you still experiencing it? I think you're the only one having this issue at the moment in the thread :stuck_out_tongue_winking_eye:

**Comment by jsnjack** [comment]
I also have an issue with latest update (1.4.0). I have vscode-icons 1.5.5, fedora 24. I updated vscode, set permissions, then clicked Icons Enable. Vscode was restarted, but icons did not appear. After it I clicked Icons Update. Vscode was restarted again, but now I see only blank screen with no decorations at all. The errors from console:
```
index.html:28 [uncaught exception]: TypeError: Cannot read property '0' of undefinedonError @ index.html:28
index.html:31 TypeError: Cannot read property '0' of undefined
    at Object.localize (loader.js:5)
    at //usr/share/code/resources/app/out/vs/workbench/workbench.main.js:63
    at e._invokeFactory (loader.js:4)
    at e._complete (loader.js:4)
    at e.resolveDependency (loader.js:4)
    at e._resolveDependency (loader.js:4)
    at e._resolve (loader.js:4)
    at e.defineModule (loader.js:4)
    at e._onLoad (loader.js:4)
    at Object.callback (loader.js:4)onError @ index.html:31
index.html:28 [uncaught exception]: TypeError: Cannot read property '0' of undefinedonError @ index.html:28
index.html:31 TypeError: Cannot read property '0' of undefined
    at Object.localize (loader.js:5)
    at //usr/share/code/resources/app/out/vs/workbench/workbench.main.js:65
    at //usr/share/code/resources/app/out/vs/workbench/workbench.main.js:65
    at e._invokeFactory (loader.js:4)
    at e._complete (loader.js:4)
    at e.resolveDependency (loader.js:4)
    at e._resolveDependency (loader.js:4)
    at e._resolve (loader.js:4)
    at e.defineModule (loader.js:4)
    at e._onLoad (loader.js:4)onError @ index.html:31
index.html:28 [uncaught exception]: TypeError: i.dirname is not a functiononError @ index.html:28
index.html:31 TypeError: i.dirname is not a function
    at //usr/share/code/resources/app/out/vs/workbench/workbench.main.js:62
    at e._invokeFactory (loader.js:4)
    at e._complete (loader.js:4)
    at e.resolveDependency (loader.js:4)
    at e._onModuleComplete (loader.js:4)
    at e._resolve (loader.js:4)
    at e.defineModule (loader.js:4)
    at e._onLoad (loader.js:4)
    at Object.callback (loader.js:4)
    at e.triggerCallback (loader.js:4)onError @ index.html:31
index.html:28 [uncaught exception]: TypeError: Cannot read property 'dialog' of undefinedonError @ index.html:28
index.html:31 TypeError: Cannot read property 'dialog' of undefined
    at //usr/share/code/resources/app/out/vs/workbench/workbench.main.js:93
    at e._invokeFactory (loader.js:4)
    at e._complete (loader.js:4)
    at e.resolveDependency (loader.js:4)
    at e._onModuleComplete (loader.js:4)
    at e._resolve (loader.js:4)
    at e.defineModule (loader.js:4)
    at e._onLoad (loader.js:4)
    at Object.callback (loader.js:4)
    at e.triggerCallback (loader.js:4)onError @ index.html:31
loader.js:4 Found an unmatched anonymous define call in the define queue. Ignoring it!
loader.js:4 (){return c}
```

**Comment by jens1o** [comment]
That was exactly the same what I found. Update successfully, but after a restart nothing works and I've got some silly exception.

@jsnjack Could you please provide, what in the file workbench.main.js is?(Round about 60) We're injecting code in this, looks like a small thing in the vscode API was changed.

**Comment by robertohuertasm** [comment]
@jsnjack unfortunately, you will have to reinstall vscode and then run Icons Enable. You followed a bad sequence. After updating, you always have to appy Icons Update, not Icons Enable. We'll have to see if we can find a way to avoid this issue in the future. 

Please, let me know if it works.

**Comment by robertohuertasm** [comment]
@jens1o is this happening to you in Windows? I've updated my editors and have had no issue in Windows. I've only detected differences between Stable and Insiders versions in terms of code but it's already managed.

**Comment by jens1o** [comment]
Yep, it's windows. My Linux VMs(stable) work beautiful with the icons. But my exception was another, it couldn't parse an else, but everything is same as he described.

**Comment by robertohuertasm** [comment]
Reinstallation and Icons Enable should do the trick, i.e. a clean install. When you reinstall all the mods are gone so it should be working flawlessly (provided that I've already tested it on Windows with no problems). You let me know what you find.

**Comment by jsnjack** [comment]
@jens1o This file is uglified, the lines are too long and Developer toolbar can't open it in Sources tab.. I'm not sure I can extract useful information for you

@robertohuertasm I reinstalled vscode and the ran Icons Enable. I still can't see the icons. This time vscode loads properly and there are no error in console

**Comment by jsnjack** [comment]
@robertohuertasm also just calling Icons Disable seems to brake the editor in the same way as Icons Update. However, the logs are different:
```
index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:28 [uncaught exception]: TypeError: Cannot read property '0' of undefinedonError @ index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:28
index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:31 TypeError: Cannot read property '0' of undefined
    at Object.localize (nls.js:61)
    at jsonContributionRegistry.ts:85
    at e._invokeFactory (loader.js:764)
    at e._complete (loader.js:776)
    at e.resolveDependency (loader.js:831)
    at e._resolveDependency (loader.js:1421)
    at e._resolve (loader.js:1519)
    at e.defineModule (loader.js:1027)
    at e._onLoad (loader.js:1118)
    at Object.callback (loader.js:1488)onError @ index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:31
index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:28 [uncaught exception]: TypeError: Cannot read property '0' of undefinedonError @ index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:28
index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:31 TypeError: Cannot read property '0' of undefined
    at Object.localize (nls.js:61)
    at suggestSupport.ts:28
    at suggestSupport.ts:62
    at e._invokeFactory (loader.js:764)
    at e._complete (loader.js:776)
    at e.resolveDependency (loader.js:831)
    at e._resolveDependency (loader.js:1421)
    at e._resolve (loader.js:1519)
    at e.defineModule (loader.js:1027)
    at e._onLoad (loader.js:1118)onError @ index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:31
index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:28 [uncaught exception]: TypeError: i.dirname is not a functiononError @ index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:28
index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:31 TypeError: i.dirname is not a function
    at package.ts:14
    at e._invokeFactory (loader.js:764)
    at e._complete (loader.js:776)
    at e.resolveDependency (loader.js:831)
    at e._onModuleComplete (loader.js:1190)
    at e._resolve (loader.js:1525)
    at e.defineModule (loader.js:1027)
    at e._onLoad (loader.js:1113)
    at Object.callback (loader.js:1488)
    at e.triggerCallback (loader.js:1559)onError @ index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:31
index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:28 [uncaught exception]: TypeError: Cannot read property 'dialog' of undefinedonError @ index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:28
index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:31 TypeError: Cannot read property 'dialog' of undefined
    at window.ts:21
    at e._invokeFactory (loader.js:764)
    at e._complete (loader.js:776)
    at e.resolveDependency (loader.js:831)
    at e._onModuleComplete (loader.js:1190)
    at e._resolve (loader.js:1525)
    at e.defineModule (loader.js:1027)
    at e._onLoad (loader.js:1113)
    at Object.callback (loader.js:1488)
    at e.triggerCallback (loader.js:1559)onError @ index.html?config={"pathArguments"%3A["%2Fhome%2Fjsn%2Fworkspace%2Fcobro%2Fdashboard"]%2C"programSt…:31
loader.js:1128 Found an unmatched anonymous define call in the define queue. Ignoring it!
loader.js:1129 (){return c}
```

**Comment by jsnjack** [comment]
@robertohuertasm ok, it started to work. I had to call Icons Disable (which broke vscode), then reinstall it and after it Icons Enable did the job!

**Comment by jens1o** [comment]
But we need to solve this Over-The-Air. There another 7k users, which are frustrated now...

**Comment by robertohuertasm** [comment]
7k? where did you get that figure Jens? :wink:  Yes, we'll have to update the readme referring to this thread and make this explicit. I agree. FAQs should be amplified with this info. Thanks @jsnjack !

**Comment by jens1o** [comment]
70k users**

https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons
Congrats to 5 Stars there :smile:

**Comment by liuchenx** [comment]
@robertohuertasm i try `Icons Enable` `Icons Update`  `reinstall vscode` not work

![image](https://cloud.githubusercontent.com/assets/8668928/17434382/b8825d10-5b3c-11e6-877c-4a81ba22c85e.png)

**Comment by jens1o** [comment]
Do you have access to the internet? Looks like the icon pack couldn't downloaded.

**Comment by robertohuertasm** [comment]
@liuchenx this picture is before icons update? after it's applied? could you be more specific at this point?

**Comment by liuchenx** [comment]
@robertohuertasm  😄  icon.zip couldn't  downloaded. i download it, work.

thx

**Comment by robertohuertasm** [comment]
@liuchenx check issue #21 It's all about proxies and how you can solve this kind of issues.
Glad you make it work! :grin: 
@jens1o you still got the issue, don't you? once we fix yours we can close this issue.

**Comment by jens1o** [comment]
@robertohuertasm No, I reinstalled vscode, then it worked normal. Only the update process causes freezing vscode.

//close

**Comment by robertohuertasm** [comment]
You say that when you execute "Icons Update" once everything is enabled your vscode freezes?

**Comment by jens1o** [comment]
Nooo. I've updated VS Code Stable via the integrated update tool, and then after the restart vscode refuses to load. Only the background was visible. The dev console said that it couldnt load *another* extension, because there was an unexpected "else" statement.

**Comment by robertohuertasm** [comment]
Ok. But I've tested here and haven't had any freezing experience. Some colleagues here have already updated their VSCode (W10) and everything worked fine after "Icons Update". We'll have to stay sharp in order to see what's causing this random freezings.

I proceed to close this issue.

**Comment by the-spyke** [comment]
I've got this issue today with updating VSCode from 1.4.0 to 1.5.1 on Linux. Already tried enabling/disabling/updating... Still no icons.

**Comment by robertohuertasm** [comment]
Can you open a separate issue?

**Comment by the-spyke** [comment]
I've already fixed it. So, I think there is no need to open an issue. After updating VSCode rewrites /usr/share/code permissions. But there is no message to restart the app with administrative permissions and icons just wont show. But there are info messages in console about those permissions. So, 'chown' on this folder fixes the issue. Thanks.

**Comment by robertohuertasm** [comment]
@the-spyke thanks for your feedback!
